### ISSUE TITLE
Target several layouts at once

### ISSUE THREAD

**Issue by madsobitsoe** [korreman/sway_bfocus#2]
Currently I cycle through tabs with 
`bindsym $mod+Tab exec sway_bfocus tabbed forward cycle`

However, I sometimes stack my windows instead of tabbing them.

Is it possible to make the cycling tab/stack agnostic?

**Comment by korreman** [comment]
This can be solved if we allow several layouts to be targeted at once, such that the first container that matches any layout included is traversed.

When cycling is disabled, moving past the edge should still traverse the next parent container that matches any of the chosen layouts. This regardless of which layout was matched before.

**Comment by korreman** [comment]
What should the syntax for this be? Current ideas:

    sway_bfocus tabbed,stacked forward cycle
    sway_bfocus forward cycle tabbed stacked

The latter seems more in line with sway config syntax.
