### ISSUE TITLE
Directional movement between outputs, floats

### ISSUE THREAD

**Issue by madsobitsoe** [korreman/sway_bfocus#3]
My setup is:
External monitor with pos: 0,0
Laptop monitor with pos: 3840,0
My external monitor is physically positioned to the left of my laptop.

The original focus command in sway allows me to 
1) Have focus in a window/container on my laptop-screen
2) Press `mod+Left`
3) Get focus on a window on my external monitor (positioned to the left of my laptop both virtually and physically) 

sway_bfocus does not transcend desktop boundaries. 

If the aim is to replace the focus command, all "active desktops", i.e. those that are currently displayed, should be taken into account when switching focus.

**Comment by korreman** [comment]
Both floats and outputs need directional movement that is based on the positions and dimensions of containers. This isn't possible to do with plain tree traversal.

The API might also need to be revamped again. I have a suspicion that there are a lot of possible edge case configurations that should be considered.

**Comment by korreman** [comment]
Features have been implemented.
